const Discord = require('discord.js');
const { totalTroops } = require('../troopmathic/troopmathic');

const template = {
    color: 0x0099ff,
    title: '<OP title>',
    timestamp: new Date(),
    footer: {
        text: 'Generated by Kabot',
        icon_url: 'https://i.imgur.com/wSTFkRM.png',
    },
};

// Populate the MessageEmbed
function loadEmbed(op, troopIndexes) {
    const embed = new Discord.MessageEmbed(template);
    
    embed.title = `Operation status: ${op.title}`;
    embed.description = `id: ${op.op_id}`;
    embed.addField('Attacker', op.attacker);
    
    if (op.status) { embed.addField('Status', op.status); }
    
    if (troopIndexes.length) {
        embed.addField('Total enlisted troops', totalTroops(troopIndexes).join('\n'));
    }
    else {
        embed.addField('Total enlisted troops', 'None');
    }
    embed.timestamp = op.createdAt;
    return embed;
}

module.exports.loadEmbed = loadEmbed;